### ISSUE TITLE
Make sure that it's possible to jump in time with the music

### ISSUE THREAD

**Issue by Sogolumbo** [bydariogamer/beatgame#11]
This can be done by adjusting the gravity accordingly.
(Assign me).

**Comment by bydariogamer** [comment]
I am not sure about what are you talking about... I will let you try anything as it keeps making the game song generated from a deterministic algorithm and not buggy; but I would like to understand what do you mean by that 😅

**Comment by Sogolumbo** [comment]
If you jump onto flat ground you will fly in a parabolic curve. The time until you touch the ground again is determined by the velocity at the beginning of the jump and the gravity. The distance between the beginning of the jump and the landing is determined by that time and the speed of the obstacles.

At the moment the distance of a jump on even ground is constant. The distance between two beats depends on the speed of the song. That means that you can only jump to the beat of songs up to a certain bpm. If the song is faster you are still in the sky when the next beat comes and can't jump.
I think this can easily be fixed by adjusting the gravity depending on the bpm.

**Comment by bydariogamer** [comment]
No need to... the double jump solves it 🤷‍♂️ 
You can try to however, but a slooow song would have little gravity then...

**Comment by bydariogamer** [comment]
That gave me an idea! If you actually implement if we can combine it with some different grounds representing different planets, with different gravity!

**Comment by bydariogamer** [comment]
I found that there are most songs are as easy to beat as in beatfeet, and some of them are even more easy, so we don't have to really really care about that now.

**Comment by Sogolumbo** [comment]
For me this is not so much about the difficulty of the levels but rather about feeling of the game.
I just think it's very satisfying when your jumps are in time with the music.

**Comment by Sogolumbo** [comment]
We can also control the height of the jumps. Maybe that's a better way to control the difficulty than the length of the jumps.

**Comment by bydariogamer** [comment]
Make some math with the double jump... if you put a parabola at any point of other parabola you can "adjust the distance" of a jump if there is an obstacle. I think at the begging I limited the falling speed (maybe you changed it 🤔 I don't remember right now, I will look for it). That would allow the player to jump at any distance.

**Comment by bydariogamer** [comment]
Solved with last PR... I will close the issue
