### ISSUE TITLE
Should the motronome 'song' stay in the game?

### ISSUE THREAD

**Issue by Sogolumbo** [bydariogamer/beatgame#12]
Do you think that the metronome 'song' is interesting enough to stay in the release version of this game?

If yes: I need to give it a license.

**Comment by bydariogamer** [comment]
I guess you meant 'Metronome'... I don't find it that bad... You can give it a free license or just use in the context of the game with GPL. Have a look at [CREDITS.md](https://github.com/bydariogamer/beatgame/blob/master/CREDITS.md) if you want. I would like the songs to be under CC-BY-SA if possible, but it is your decision.

**Comment by bydariogamer** [comment]
I think this issue is solved now. Thanks for using a free license.
