### ISSUE TITLE
Moving some variables to a _constants.py_ file

### ISSUE THREAD

**Issue by bydariogamer** [bydariogamer/beatgame#15]
I think some variables like `BASE_FPS`, `DISP_WID`, `DISP_HEI` etcetera should go into a separated file `constants.py` so they can be used in any place without making weird circular imports.

**Comment by Sogolumbo** [comment]
Yes I agree. Maybe `config.py` is a better name.

**Comment by Sogolumbo** [comment]
I think the code will be easier to understand if the constants are called with `config.disp_width` instead of `disp_width` appearing 'out of nowhere'.

**Comment by bydariogamer** [comment]
Accepted PR. Issues solved.
