### ISSUE TITLE
some weird code I can't understand

### ISSUE THREAD

**Issue by bydariogamer** [bydariogamer/beatgame#17]
Just: what is this???
```            while max_index == 0 + a or max_index == length-1-b:
                if max_index == 0 + a:```
I mean, why `a+0`... don't you know 0 plus any number is the same number 😉 ?

**Comment by bydariogamer** [comment]
I will add some code I just don't understand here, so don't close the issue too soon.
Also, do you mind if I give code a bit of style? Like, deleting some excessive newlines, add space around some operators, delete some redundant parenthesis? Maybe you prefer to PR all stuff first and then I do the cleanup...

**Comment by Sogolumbo** [comment]
Oops.
I guess i had ` if max_index == 0` first and then I found out that I need to add `a` to the constant and didn't question that contant (0).

**Comment by Sogolumbo** [comment]
I never really learned styling conventions in python. My first programming languages were Java and C#, the 'unecessary' parantheses are just muscle memory.

**Comment by Sogolumbo** [comment]
And with a nice IDE you can automatically fix the operator spacings. You're welcome to adapt my code to your style. Just make it a separate commit in which no functionality changes so it's easier to merge.

**Comment by bydariogamer** [comment]
I will do a styling branch... The code development will work then like:
- Merge to algorithm, particles, high-score... or whatever branch
- Merge to development to put all the stuff together and resolve the bugs created by the merge
- Style the code
- Publish in main
- Make release
