### ISSUE TITLE
The songs and the signals created from the songs are not in sync

### ISSUE THREAD

**Issue by Sogolumbo** [bydariogamer/beatgame#3]
I think there are multiple issues here:
1. The speed of the sound and the speed of the signal controlling the block height don't match
2. There's an offset between the time at which the user needs to press the jump and the sound. Ideally the user would need to press in time. But for an easier start I would already be happy if the blocks would arrive at the player position at the same time as the corresponding audio is played.

**Comment by bydariogamer** [comment]
I tried to make the calculus by hand, but I was unable. It would be great if someone had an idea of how to actually sync them...
I will try to implement it as soon as possible but I will have to figure out how to solve the problem of passing from the floating maths of the sample parsing to the integer maths of rectangle drawing... At the very beginning there wasn't this issue but there horrible gaps between many rects making the gameplay difficult.

**Comment by bydariogamer** [comment]
WOOOOOW! You actually improved the algorithm. And the time it takes to load a song is just slightly longer than it used to... You improved it a lot, levels are incredible now. A lot of thanks!

**Comment by Sogolumbo** [comment]
I fixed most of the issues.

But one problem remains: The fps are not very stable (should be at 60, but they vary quite a bit as you can see in the histogram below).
![beatgame fps histogram](https://user-images.githubusercontent.com/33571916/114953724-4c0b0280-9e59-11eb-9215-99aa9433768c.png)

So relying on them to keep the obstacles at the right position does not work. This variation leads to up to ~0.6s of misalignment between the obstacles and the audio.

Instead the position of the obstacles should be calculated based on the time which has passed since the song started.

**Comment by bydariogamer** [comment]
That is terrible actually, but can  be done creating a variable to store the misalignment and when it is bigger than (certain) we change all `obstacle.x`.

**Comment by Sogolumbo** [comment]
That sems like the worst workaround ever. I already fixed the timing issues.

The [last fix I did](https://github.com/Sogolumbo/beatgame/commit/5b7d7e56f0a2548efbeea8003a85e4b71d8e04b6) seems to have had an incredibly strong effect.
Please remember this: When you need something to be an integer and (at least kind of accurate): use round() instead of int(). And don't round anything until the very last possible moment. This will avoid accumilating rounding errors.

**Comment by bydariogamer** [comment]
I will still use it in cases where there is no need to update the variable... (I am trying to make the particles system a bit better)

I added some to-does so you can see some decisions before I commit them or maybe you can decide how to improve them
