### ISSUE TITLE
Particles (basic functionality)

### ISSUE THREAD

**Issue by Sogolumbo** [bydariogamer/beatgame#6]
I see we are working on the same bugs at the same time, that's not very effective.
I need you give me a boolean which states whether the player is touching the ground.
Then we can use that boolean to trigger particle creation and deletion and improve the code readability.

**Comment by bydariogamer** [comment]
The player is touching ground when `self.vel_y == 0`... It is valid for almost every frame.
That's a lazy solution however I guess. I will work at it after the stars... I can turn particles down (I am not good at particles 😢 but I think background is something I should have done from the very beginning)

**Comment by Sogolumbo** [comment]
The lazy solution also has the problem of deleting particles at the beginning of the jump, which I think doesn't look that nice.

**Comment by Sogolumbo** [comment]
I think the code is already able to detect if someone is touching the ground.
I can try and find that point on my own too.

**Comment by bydariogamer** [comment]
Yea, I show the problem with particles now (the particles are cleaned when character raise top of its jump due to `vel_y == 0`...
I will let you code that part now... I m figuring out how to add stars that are not too annoying... I need to distribute in the screen both uniform and random I guess.
A _BIG_ idea: the number of stars increases with the combo!

**Comment by Sogolumbo** [comment]
https://numpy.org/doc/stable/reference/random/generated/numpy.random.uniform.html

**Comment by Sogolumbo** [comment]
I would've just generated a sky with the stars as part of the level generation.

**Comment by bydariogamer** [comment]
I am making stars different. Also, the new velocities system is a bit harder to use with backgrounds... It is easy to solve however. I think I _won't_ improve the level's background synchrony with music.
I am just using `random` module, although using an array might be easier to update.
I am also thinking stars may blink a little bit... Like from (250, 250, 250,) to (200, 200, 200). It would be easy not that difficult to update and might make sky more animated.

**Comment by Sogolumbo** [comment]
yeah, blinking is cool.
The stars are not time critical and they will move at a different speed than the music anyways. So you can set a `star_speed = 100 # pixels per second` and then move the stars on every frame: `star.x -= star_speed/fps`

**Comment by bydariogamer** [comment]
I think stars basics and particles basics issues are solved right now. I may do a new release by the end of the day so some friends can try it.

**Comment by Sogolumbo** [comment]
I'm closing this as the basic functionality of the air-time particles is working (I don't consider stars as particles but as background).
